# Generated by Django 4.1 on 2023-07-25 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0003_alter_profile_retire_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('body', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Body')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.profile')),
            ],
        ),
    ]
