# Generated by Django 4.2.2 on 2023-11-24 09:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('body', ckeditor.fields.RichTextField(null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('snippet', models.TextField(max_length=300, null=True, verbose_name='snippet')),
            ],
        ),
    ]
