# Generated by Django 4.1 on 2023-07-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='snippet',
            field=models.CharField(max_length=300, null=True, verbose_name='Title'),
        ),
    ]
