# Generated by Django 4.1 on 2023-07-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='snippet',
            field=models.TextField(max_length=300, null=True, verbose_name='snippet'),
        ),
    ]
