# Generated by Django 4.2.2 on 2023-07-13 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('event_datetime', models.DateTimeField(verbose_name='Event Date')),
                ('duration', models.CharField(choices=[('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('others', 'others')], max_length=10, null=True)),
                ('max_players', models.SmallIntegerField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Event price')),
                ('activity_note', models.TextField(blank=True, max_length=200, null=True)),
                ('payment_qr', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=120, verbose_name='Venue Address')),
                ('venue_type', models.CharField(blank=True, choices=[('indoor', 'indoor'), ('outdoor', 'outdoor')], max_length=30, null=True)),
                ('note', models.TextField(blank=True, max_length=500, verbose_name='Venue Note')),
            ],
        ),
        migrations.CreateModel(
            name='RSVP_Profile_inter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RSVP_datetime', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=50, null=True, verbose_name='note')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
            ],
        ),
    ]
