# Generated by Django 4.1 on 2023-06-23 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event Name')),
                ('date', models.DateTimeField(verbose_name='Event Date')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Event price')),
                ('activity_note', models.TextField(blank=True, max_length=200, null=True)),
                ('payment_qr', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Venue Name')),
                ('address', models.CharField(max_length=120, verbose_name='Venue Address')),
                ('note', models.TextField(max_length=500, verbose_name='Venue Note')),
            ],
        ),
        migrations.CreateModel(
            name='RSVP_Profile_inter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RSVP_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.profile')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='RSVP',
            field=models.ManyToManyField(blank=True, null=True, through='event.RSVP_Profile_inter', to='members.profile'),
        ),
        migrations.AddField(
            model_name='event',
            name='organiser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.venue'),
        ),
    ]
