# Generated by Django 4.1 on 2023-06-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp_profile_inter',
            name='note',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='note'),
        ),
    ]
