# Generated by Django 4.1 on 2023-06-23 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_rsvp_profile_inter_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp_profile_inter',
            name='RSVP_datetime',
        ),
    ]
