# Generated by Django 4.2.2 on 2023-07-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(max_length=200, null=True, verbose_name='Venue address'),
        ),
        migrations.DeleteModel(
            name='Venue',
        ),
    ]
