# Generated by Django 4.1 on 2023-06-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_remove_rsvp_profile_inter_rsvp_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp_profile_inter',
            name='RSVP_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
