# Generated by Django 4.1 on 2023-06-26 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_rsvp_profile_inter_rsvp_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='event_datetime',
        ),
    ]
