# Generated by Django 4.1 on 2023-06-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_rename_date_event_event_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.CharField(choices=[(1, '1'), (1.5, 'yidianwu')], max_length=10, null=True),
        ),
    ]
