# Generated by Django 4.1 on 2023-06-26 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_event_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(blank=True, choices=[('indoor', 'indoor'), ('outdoor', 'outdoor')], max_length=30, null=True),
        ),
    ]
