# Generated by Django 4.1 on 2023-06-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_venue_venue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='note',
            field=models.TextField(blank=True, max_length=500, verbose_name='Venue Note'),
        ),
    ]
