# Generated by Django 4.1 on 2023-06-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_event_organiser'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='max_players',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
