# Generated by Django 4.2.2 on 2023-06-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_profile_player_type'),
        ('event', '0013_event_max_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='RSVP',
            field=models.ManyToManyField(blank=True, through='event.RSVP_Profile_inter', to='members.profile'),
        ),
    ]
