# Generated by Django 4.1 on 2023-07-31 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_images',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='shop/'),
        ),
    ]
