# Generated by Django 4.1 on 2023-06-23 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, null=True, verbose_name='Last Name')),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nick Name')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Member Age')),
                ('email', models.EmailField(max_length=50, null=True, verbose_name='Member Email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Member Phone')),
                ('shirt_size', models.CharField(blank=True, max_length=20, null=True, verbose_name='Shirt Size')),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Member Bio')),
                ('player_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'caiji'), (2, 'master')], null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
