# Generated by Django 4.1 on 2023-06-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='player_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '休闲'), (2, '野人')], null=True),
        ),
    ]
